CATEGORY_NAMES = {
  PR: 'Private Residence',
  NF: 'National Forest',
  SP: 'State Park',
  CP: 'County Park',
  CITY: 'City Park',
  PL: 'Parking Lot',
  PP: 'Private RV Park',
  NP: 'National Park',
  CC: 'County Park',
  ARMY: 'Army Corps of Engineers',
  MFW: 'Montana Fish & Wildlife',
  SF: 'State Forest Campground',
  BLMB: 'BLM Boondocking',
  BLM: 'BLM Campground',
  SPB: 'State Park Boondocking',
  NFB: 'National Forest Boondocking',
  NPB: 'National Park Boondocking',
  TVA: 'Tennessee Valley Authority'
}
