
STATE_ABBR = {
  'AL' => 'Alabama',
  'AK' => 'Alaska',
  'AS' => 'America Samoa',
  'AZ' => 'Arizona',
  'AR' => 'Arkansas',
  'CA' => 'California',
  'CO' => 'Colorado',
  'CT' => 'Connecticut',
  'DE' => 'Delaware',
  'DC' => 'District of Columbia',
  'FM' => 'Micronesia1',
  'FL' => 'Florida',
  'GA' => 'Georgia',
  'GU' => 'Guam',
  'HI' => 'Hawaii',
  'ID' => 'Idaho',
  'IL' => 'Illinois',
  'IN' => 'Indiana',
  'IA' => 'Iowa',
  'KS' => 'Kansas',
  'KY' => 'Kentucky',
  'LA' => 'Louisiana',
  'ME' => 'Maine',
  'MH' => 'Islands1',
  'MD' => 'Maryland',
  'MA' => 'Massachusetts',
  'MI' => 'Michigan',
  'MN' => 'Minnesota',
  'MS' => 'Mississippi',
  'MO' => 'Missouri',
  'MT' => 'Montana',
  'NE' => 'Nebraska',
  'NV' => 'Nevada',
  'NH' => 'New Hampshire',
  'NJ' => 'New Jersey',
  'NM' => 'New Mexico',
  'NY' => 'New York',
  'NC' => 'North Carolina',
  'ND' => 'North Dakota',
  'OH' => 'Ohio',
  'OK' => 'Oklahoma',
  'OR' => 'Oregon',
  'PW' => 'Palau',
  'PA' => 'Pennsylvania',
  'PR' => 'Puerto Rico',
  'RI' => 'Rhode Island',
  'SC' => 'South Carolina',
  'SD' => 'South Dakota',
  'TN' => 'Tennessee',
  'TX' => 'Texas',
  'UT' => 'Utah',
  'VT' => 'Vermont',
  'VI' => 'Virgin Island',
  'VA' => 'Virginia',
  'WA' => 'Washington',
  'WV' => 'West Virginia',
  'WI' => 'Wisconsin',
  'WY' => 'Wyoming'
}


STATE_FACE = {
  VA: "s",
  ND: "b",
  NY: "h",
  AL: "B",
  RI: "m",
  NE: "c",
  MN: "W",
  MD: "T",
  HI: "K",
  DE: "H",
  CO: "F",
  WY: "x",
  MO: "X",
  ME: "U",
  IA: "L",
  OR: "k",
  OH: "i",
  KY: "Q",
  IL: "N",
  AZ: "D",
  TX: "q",
  TN: "p",
  NH: "d",
  GA: "J",
  SC: "n",
  IN: "O",
  ID: "M",
  SD: "o",
  PA: "l",
  OK: "j",
  NJ: "e",
  MS: "Y",
  MI: "V",
  FL: "I",
  CT: "G",
  AR: "C",
  WI: "v",
  MT: "Z",
  US: "z",
  VT: "t",
  NV: "g",
  KS: "P",
  CA: "E",
  WV: "w",
  UT: "r",
  NM: "f",
  MA: "S",
  DC: "y",
  WA: "u",
  NC: "a",
  LA: "R",
  AK: "A",
  PR: "3"
}
